### ISSUE TITLE
App Throws Error On Fedora 31 x64

### ISSUE THREAD

**Issue by progkix** [sidneys/desktop-dimmer#49]
## 🤷🏽‍♂️ Current Behaviour
Application fails to run on Fedora 31 x64

(desktop-dimmer:2206266): Pango-ERROR **: 03:17:55.384: Harfbuzz version too old (1.2.7)

Trace/breakpoint trap (core dumped)

## 🎯 Expected Behaviour
Application should run

## 👟 Steps to Reproduce (S2R)
 1. At command prompt, enter desktop-dimmer

## 🏡 Environmental Context
4.0.4
**Installation Type** 
RPM
**Operating System**
Fedora 31 x64
Pango 1.44.7-1
Harfbuzz 2.6.1-2

**Comment by progkix** [comment]
I have also tried build from source and get the following error:

root@lnx1 desktop-dimmer-4.0.4]# npm run build

> desktop-dimmer@4.0.4 build /usr/local/src/desktop-dimmer-4.0.4
> node ./node_modules/@sidneys/electron-build/index.js

internal/modules/cjs/loader.js:775
    throw err;
    ^

Error: Cannot find module '/usr/local/src/desktop-dimmer-4.0.4/node_modules/@sidneys/electron-build/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! desktop-dimmer@4.0.4 build: `node ./node_modules/@sidneys/electron-build/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the desktop-dimmer@4.0.4 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-12T07_08_59_092Z-debug.log

**Comment by ylluminarious** [comment]
I'm getting this error too on Ubuntu 20.04. I upgraded all my packages to make sure everything was up-to-date, but no luck. The error still didn't go away.

@sidneys Any ideas on how to fix this?

**Comment by ylluminarious** [comment]
It appears that this issue has to do with needing to build against a newer version of libpango. Here are some links discussing this issue that I found:

- https://askubuntu.com/questions/1259443/pango-error-harfbuzz-version-too-old-1-4-2
- https://github.com/electron/electron/issues/20348
- https://unix.stackexchange.com/questions/589993/pango-error-harfbuzz-version-too-old

Unfortunately, I see no way to fix the problem without submitting a PR. So, I found a workaround via the `xrandr` command. You can use this to set the brightness down and a achieve a similar effect to `desktop-dimmer`. Here is an article which explains how to do this: https://www.how2shout.com/how-to/how-to-change-screen-brightness-in-ubuntu-using-command-terminal.html

You can also use set `xrandr`'s arguments so that it retains Night Light-like colors, while also dimming the screen: https://askubuntu.com/questions/1003101/how-to-use-xrandr-gamma-for-gnome-night-light-like-usage

Until `desktop-dimmer` is fixed, I'll probably just stick to this workaround. But since it's been out of development for 3 years, I'm not sure if/when it'll be updated... oh well 🤷‍♂️

**Comment by irodionzaytsev** [comment]
This is why people prefer macs over ubuntu. Typical UNIX-way solution: here are a copule of utterly useless commands which could wipe your computer, we aren't going to change anything. Honestly, installing a new bit of software on ubuntu is such a pain that it might be used as intellectual torture. I know it's not your fault, but all I'm saying, is that before we overcome this idiocy, linux will remain a buggy resort for people who can't afford macs.
